config/routes.rb
Rails.application.routes.draw do
  resources :encounters
  resources :places
  devise_for :users
  root to: 'games#new'
  get 'games/new'
  post 'games/draw'
  get 'games/reward'
end

app/models/encounter.rb
class Encounter < ActiveRecord::Base
  belongs_to :user
end

app/models/game.rb
class Game
  attr_accessor :risk
  include ActiveModel::Model
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user
end

app/models/reward.rb
class Reward
  attr_accessor :type, :points

  def initialize(type, points)
    @type = type
    @points = points
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
  before_action :set_encounter, only: [:show, :edit, :update, :destroy]

  # GET /encounters
  # GET /encounters.json
  def index
    @encounters = Encounter.where(user: current_user)
  end

  # GET /encounters/1
  # GET /encounters/1.json
  def show
  end

  # GET /encounters/new
  def new
    @encounter = Encounter.new
  end

  # GET /encounters/1/edit
  def edit
  end

  # POST /encounters
  # POST /encounters.json
  def create
    @encounter = Encounter.new(encounter_params)
    @encounter.user = current_user
    respond_to do |format|
      if @encounter.save
        format.html { redirect_to @encounter, notice: 'Encounter was successfully created.' }
        format.json { render :show, status: :created, location: @encounter }
      else
        format.html { render :new }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /encounters/1
  # PATCH/PUT /encounters/1.json
  def update
    respond_to do |format|
      if @encounter.update(encounter_params)
        format.html { redirect_to @encounter, notice: 'Encounter was successfully updated.' }
        format.json { render :show, status: :ok, location: @encounter }
      else
        format.html { render :edit }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encounters/1
  # DELETE /encounters/1.json
  def destroy
    @encounter.destroy
    respond_to do |format|
      format.html { redirect_to encounters_url, notice: 'Encounter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_encounter
      @encounter = Encounter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def encounter_params
      params.require(:encounter).permit(:name, :description, :frequency)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @game = Game.new
  end

  def draw
    draw = Draw.new(game_params[:risk]).call
    @place = draw[:place]
    @encounters = draw[:encounters]
    @risk = game_params[:risk]
  end

  def reward
    @rewards = DrawReward.new(params[:risk]).call
  end

  private

  def game_params
    params.require(:game).permit(:risk)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.where(user: current_user)
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    @place.user = current_user
    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, :frequency)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/encounters/_form.html.haml
= simple_form_for(@encounter) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :frequency

  .form-actions
    = f.button :submit

app/views/encounters/edit.html.haml
%h1 Editing encounter

= render 'form'

= link_to 'Show', @encounter
\|
= link_to 'Back', encounters_path

app/views/encounters/index.html.haml
%h1 Listing encounters

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Frequency
      %th
      %th
      %th

  %tbody
    - @encounters.each do |encounter|
      %tr
        %td= encounter.name
        %td= encounter.description
        %td= encounter.frequency
        %td= link_to 'Show', encounter
        %td= link_to 'Edit', edit_encounter_path(encounter)
        %td= link_to 'Destroy', encounter, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Encounter', new_encounter_path

app/views/encounters/new.html.haml
%h1 New encounter

= render 'form'

= link_to 'Back', encounters_path

app/views/encounters/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @encounter.name
%p
  %b Description:
  = @encounter.description
%p
  %b Frequency:
  = @encounter.frequency

= link_to 'Edit', edit_encounter_path(@encounter)
\|
= link_to 'Back', encounters_path

app/views/games/draw.haml
%h3 Place
%strong.name
  = @place.name
  %span{ style: 'font-size: small' }= "(#{@place.user.email})"
.description
  = @place.description

%h3 Encounters
- @encounters.each do |encounter|
  %strong.name
    = encounter.name
    %span{ style: 'font-size: small' }= "(#{encounter.user.email})"
  .description
    = encounter.description

.reward-actions{ style: 'margin-top: 20px;' }
  = link_to 'Reward', games_reward_path(risk: @risk), class: 'btn btn-success'
  = link_to 'No reward', games_new_path, class: 'btn btn-danger'

app/views/games/new.haml
= simple_form_for @game, url: games_draw_path do |f|
  = f.input :risk, as: :radio_buttons, collection: [1,2,3]
  = f.submit

app/views/games/reward.haml
- if @rewards.count == 0
  No rewards, you fool
- @rewards.each do |reward|
  %p
    = reward.type.titleize
    x
    = reward.points

.actions
  = link_to 'Next round', games_new_path, class: 'btn btn-default'

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Survive!', root_path, class: 'navbar-brand'
      = link_to 'Places', places_path, class: 'navbar-brand'
      = link_to 'Encounter', encounters_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Survivalrpg'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Survivalrpg'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/places/_form.html.haml
= simple_form_for(@place) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :frequency

  .form-actions
    = f.button :submit

app/views/places/edit.html.haml
%h1 Editing place

= render 'form'

= link_to 'Show', @place
\|
= link_to 'Back', places_path

app/views/places/index.html.haml
%h1 Listing places

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Frequency
      %th
      %th
      %th

  %tbody
    - @places.each do |place|
      %tr
        %td= place.name
        %td= place.description
        %td= place.frequency
        %td= link_to 'Show', place
        %td= link_to 'Edit', edit_place_path(place)
        %td= link_to 'Destroy', place, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Place', new_place_path

app/views/places/new.html.haml
%h1 New place

= render 'form'

= link_to 'Back', places_path

app/views/places/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @place.name
%p
  %b Description:
  = @place.description
%p
  %b Frequency:
  = @place.frequency

= link_to 'Edit', edit_place_path(@place)
\|
= link_to 'Back', places_path